apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation-webhook-example-cfg
  labels:
    app: admission-webhook-example
webhooks:
  - name: required-labels.banzaicloud.com
    clientConfig:
      service:
        name: admission-webhook-example-svc
        namespace: default
        path: "/validate"
      caBundle: ${CA_BUNDLE}
    rules:

      # Rules as per Banzai Cloud example: ------------
      #- operations: [ "CREATE" ]
      #  apiGroups: ["apps", ""]
      #  apiVersions: ["v1"]
      #  resources: ["deployments","services"]

      # Rules to see EVERY REQUEST: ------------
      - operations: [ "*" ]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["deployments","services"]
        #resources: ["*"]

    namespaceSelector:
      matchLabels:
        admission-webhook-example: enabled
